package com.vz.cassandraTool.pojo;
// Generated Nov 12, 2019 12:28:09 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CassandraTable generated by hbm2java
 */
@Entity
@Table(name = "cassandra_table", catalog = "cassandra_automation1")
public class CassandraTable implements java.io.Serializable {

	private Integer cassandraTableId;
	private SourceTable sourceTable;
	private String cassandraTableName;
	private String controlFileName;
	private Set<JobRun> jobRuns = new HashSet<JobRun>(0);

	public CassandraTable() {
	}

	public CassandraTable(SourceTable sourceTable, String cassandraTableName) {
		this.sourceTable = sourceTable;
		this.cassandraTableName = cassandraTableName;
	}

	public CassandraTable(SourceTable sourceTable, String cassandraTableName, String controlFileName,
			Set<JobRun> jobRuns) {
		this.sourceTable = sourceTable;
		this.cassandraTableName = cassandraTableName;
		this.controlFileName = controlFileName;
		this.jobRuns = jobRuns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cassandraTableId", unique = true, nullable = false)
	public Integer getCassandraTableId() {
		return this.cassandraTableId;
	}

	public void setCassandraTableId(Integer cassandraTableId) {
		this.cassandraTableId = cassandraTableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sourceTableId", nullable = false)
	public SourceTable getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(SourceTable sourceTable) {
		this.sourceTable = sourceTable;
	}

	@Column(name = "cassandraTableName", nullable = false, length = 100)
	public String getCassandraTableName() {
		return this.cassandraTableName;
	}

	public void setCassandraTableName(String cassandraTableName) {
		this.cassandraTableName = cassandraTableName;
	}

	@Column(name = "controlFileName", length = 100)
	public String getControlFileName() {
		return this.controlFileName;
	}

	public void setControlFileName(String controlFileName) {
		this.controlFileName = controlFileName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cassandraTable")
	public Set<JobRun> getJobRuns() {
		return this.jobRuns;
	}

	public void setJobRuns(Set<JobRun> jobRuns) {
		this.jobRuns = jobRuns;
	}

}
