package com.vz.cassandraTool.pojo;
// Generated Nov 12, 2019 12:28:09 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FileProcess generated by hbm2java
 */
@Entity
@Table(name = "file_process", catalog = "cassandra_automation1")
public class FileProcess implements java.io.Serializable {

	private int fileProcessId;
	private ErrorLog errorLog;
	private JobRun jobRun;
	private String status;

	public FileProcess() {
	}

	public FileProcess(int fileProcessId) {
		this.fileProcessId = fileProcessId;
	}

	public FileProcess(int fileProcessId, ErrorLog errorLog, JobRun jobRun, String status) {
		this.fileProcessId = fileProcessId;
		this.errorLog = errorLog;
		this.jobRun = jobRun;
		this.status = status;
	}

	@Id

	@Column(name = "fileProcessId", unique = true, nullable = false)
	public int getFileProcessId() {
		return this.fileProcessId;
	}

	public void setFileProcessId(int fileProcessId) {
		this.fileProcessId = fileProcessId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "errorCode")
	public ErrorLog getErrorLog() {
		return this.errorLog;
	}

	public void setErrorLog(ErrorLog errorLog) {
		this.errorLog = errorLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobRunId")
	public JobRun getJobRun() {
		return this.jobRun;
	}

	public void setJobRun(JobRun jobRun) {
		this.jobRun = jobRun;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
