package com.vz.cassandraTool.domainClass;
// Generated Oct 16, 2019 12:26:37 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cassandratables generated by hbm2java
 */
@Entity
@Table(name = "cassandratables", catalog = "cassandra_automation")
public class Cassandratables implements java.io.Serializable {

	private int cassandraTableId;
	private SourceTable sourceTable;
	private String cassandraTableName;
	private String controlFileName;
	private Set<JobRun> jobRuns = new HashSet<JobRun>(0);

	public Cassandratables() {
	}

	public Cassandratables(int cassandraTableId, String cassandraTableName) {
		this.cassandraTableId = cassandraTableId;
		this.cassandraTableName = cassandraTableName;
	}

	public Cassandratables(int cassandraTableId, SourceTable sourceTable, String cassandraTableName,
			String controlFileName, Set<JobRun> jobRuns) {
		this.cassandraTableId = cassandraTableId;
		this.sourceTable = sourceTable;
		this.cassandraTableName = cassandraTableName;
		this.controlFileName = controlFileName;
		this.jobRuns = jobRuns;
	}

	@Id

	@Column(name = "cassandra_table_id", unique = true, nullable = false)
	public int getCassandraTableId() {
		return this.cassandraTableId;
	}

	public void setCassandraTableId(int cassandraTableId) {
		this.cassandraTableId = cassandraTableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "source_table_id")
	public SourceTable getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(SourceTable sourceTable) {
		this.sourceTable = sourceTable;
	}

	@Column(name = "cassandra_table_name", nullable = false, length = 100)
	public String getCassandraTableName() {
		return this.cassandraTableName;
	}

	public void setCassandraTableName(String cassandraTableName) {
		this.cassandraTableName = cassandraTableName;
	}

	@Column(name = "control_file_name", length = 100)
	public String getControlFileName() {
		return this.controlFileName;
	}

	public void setControlFileName(String controlFileName) {
		this.controlFileName = controlFileName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cassandratables")
	public Set<JobRun> getJobRuns() {
		return this.jobRuns;
	}

	public void setJobRuns(Set<JobRun> jobRuns) {
		this.jobRuns = jobRuns;
	}

}
