package com.vz.cassandraTool.domainClass;
// Generated Nov 12, 2019 10:28:42 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobRun generated by hbm2java
 */
@Entity
@Table(name = "job_run", catalog = "cassandra_automation")
public class JobRun implements java.io.Serializable {

	private int jobRunId;
	private SourceTable sourceTable;
	private System system;
	private int cassandraId;
	private String environmentName;
	private String instanceName;
	private String frequency;
	private String feedFileName;
	private Byte isReconFile;
	private String status;

	public JobRun() {
	}

	public JobRun(int jobRunId, SourceTable sourceTable, System system, int cassandraId) {
		this.jobRunId = jobRunId;
		this.sourceTable = sourceTable;
		this.system = system;
		this.cassandraId = cassandraId;
	}

	public JobRun(int jobRunId, SourceTable sourceTable, System system, int cassandraId, String environmentName,
			String instanceName, String frequency, String feedFileName, Byte isReconFile, String status) {
		this.jobRunId = jobRunId;
		this.sourceTable = sourceTable;
		this.system = system;
		this.cassandraId = cassandraId;
		this.environmentName = environmentName;
		this.instanceName = instanceName;
		this.frequency = frequency;
		this.feedFileName = feedFileName;
		this.isReconFile = isReconFile;
		this.status = status;
	}

	@Id

	@Column(name = "job_run_id", unique = true, nullable = false)
	public int getJobRunId() {
		return this.jobRunId;
	}

	public void setJobRunId(int jobRunId) {
		this.jobRunId = jobRunId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "source_id", nullable = false)
	public SourceTable getSourceTable() {
		return this.sourceTable;
	}

	public void setSourceTable(SourceTable sourceTable) {
		this.sourceTable = sourceTable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "system_id", nullable = false)
	public System getSystem() {
		return this.system;
	}

	public void setSystem(System system) {
		this.system = system;
	}

	@Column(name = "cassandra_id", nullable = false)
	public int getCassandraId() {
		return this.cassandraId;
	}

	public void setCassandraId(int cassandraId) {
		this.cassandraId = cassandraId;
	}

	@Column(name = "environment_name", length = 45)
	public String getEnvironmentName() {
		return this.environmentName;
	}

	public void setEnvironmentName(String environmentName) {
		this.environmentName = environmentName;
	}

	@Column(name = "instance_name", length = 45)
	public String getInstanceName() {
		return this.instanceName;
	}

	public void setInstanceName(String instanceName) {
		this.instanceName = instanceName;
	}

	@Column(name = "frequency", length = 45)
	public String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	@Column(name = "feed_file_name", length = 45)
	public String getFeedFileName() {
		return this.feedFileName;
	}

	public void setFeedFileName(String feedFileName) {
		this.feedFileName = feedFileName;
	}

	@Column(name = "is_recon_file")
	public Byte getIsReconFile() {
		return this.isReconFile;
	}

	public void setIsReconFile(Byte isReconFile) {
		this.isReconFile = isReconFile;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
