package com.vz.cassandraTool.domainClass;
// Generated Nov 12, 2019 10:28:42 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SourceTable generated by hbm2java
 */
@Entity
@Table(name = "source_table", catalog = "cassandra_automation")
public class SourceTable implements java.io.Serializable {

	private Integer sourceTableId;
	private System system;
	private String sourceTableName;
	private Byte reference;
	private Set<JobRun> jobRuns = new HashSet<JobRun>(0);

	public SourceTable() {
	}

	public SourceTable(System system, String sourceTableName, Byte reference, Set<JobRun> jobRuns) {
		this.system = system;
		this.sourceTableName = sourceTableName;
		this.reference = reference;
		this.jobRuns = jobRuns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "source_table_Id", unique = true, nullable = false)
	public Integer getSourceTableId() {
		return this.sourceTableId;
	}

	public void setSourceTableId(Integer sourceTableId) {
		this.sourceTableId = sourceTableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "system_id")
	public System getSystem() {
		return this.system;
	}

	public void setSystem(System system) {
		this.system = system;
	}

	@Column(name = "source_table_name", length = 45)
	public String getSourceTableName() {
		return this.sourceTableName;
	}

	public void setSourceTableName(String sourceTableName) {
		this.sourceTableName = sourceTableName;
	}

	@Column(name = "reference")
	public Byte getReference() {
		return this.reference;
	}

	public void setReference(Byte reference) {
		this.reference = reference;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sourceTable")
	public Set<JobRun> getJobRuns() {
		return this.jobRuns;
	}

	public void setJobRuns(Set<JobRun> jobRuns) {
		this.jobRuns = jobRuns;
	}

}
