package com.vz.cassandraTool.pojo;
// Generated Nov 12, 2019 12:28:09 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jobs generated by hbm2java
 */
@Entity
@Table(name = "jobs", catalog = "cassandra_automation1")
public class Jobs implements java.io.Serializable {

	private Integer jobId;
	private String jobName;
	private Byte isRecon;
	private Set<SourceTable> sourceTables = new HashSet<SourceTable>(0);

	public Jobs() {
	}

	public Jobs(String jobName, Byte isRecon, Set<SourceTable> sourceTables) {
		this.jobName = jobName;
		this.isRecon = isRecon;
		this.sourceTables = sourceTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "jobId", unique = true, nullable = false)
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	@Column(name = "jobName", length = 45)
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Column(name = "isRecon")
	public Byte getIsRecon() {
		return this.isRecon;
	}

	public void setIsRecon(Byte isRecon) {
		this.isRecon = isRecon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<SourceTable> getSourceTables() {
		return this.sourceTables;
	}

	public void setSourceTables(Set<SourceTable> sourceTables) {
		this.sourceTables = sourceTables;
	}

}
