package com.vz.cassandraTool.pojo;
// Generated Nov 12, 2019 12:28:09 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * SourceTable generated by hbm2java
 */
@Entity
@Table(name = "source_table", catalog = "cassandra_automation1")
@JsonIgnoreProperties
public class SourceTable implements java.io.Serializable {

	private Integer sourceTableId;
	private Jobs jobs;
	private System system;
	private String sourceTableName;
	private Boolean reference;
	private String confFileName;
	private Set<JobRun> jobRuns = new HashSet<JobRun>(0);
	private Set<CassandraTable> cassandraTables = new HashSet<CassandraTable>(0);
	public SourceTable() {
	}

	public SourceTable(Jobs jobs, System system, String sourceTableName, Boolean reference, String confFileName,
			Set<JobRun> jobRuns, Set<CassandraTable> cassandraTables) {
		this.jobs = jobs;
		this.system = system;
		this.sourceTableName = sourceTableName;
		this.reference = reference;
		this.confFileName = confFileName;
		this.jobRuns = jobRuns;
		this.cassandraTables = cassandraTables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sourceTableId", unique = true, nullable = false)
	public Integer getSourceTableId() {
		return this.sourceTableId;
	}

	public void setSourceTableId(Integer sourceTableId) {
		this.sourceTableId = sourceTableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobId")
	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "systemId")
	public System getSystem() {
		return this.system;
	}

	public void setSystem(System system) {
		this.system = system;
	}

	@Column(name = "sourceTableName", length = 45)
	public String getSourceTableName() {
		return this.sourceTableName;
	}

	public void setSourceTableName(String sourceTableName) {
		this.sourceTableName = sourceTableName;
	}

	@Column(name = "reference")
	public Boolean getReference() {
		return this.reference;
	}

	public void setReference(Boolean reference) {
		this.reference = reference;
	}

	@Column(name = "confFileName", length = 100)
	public String getConfFileName() {
		return this.confFileName;
	}

	public void setConfFileName(String confFileName) {
		this.confFileName = confFileName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sourceTable")
	public Set<JobRun> getJobRuns() {
		return this.jobRuns;
	}

	public void setJobRuns(Set<JobRun> jobRuns) {
		this.jobRuns = jobRuns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sourceTable")
	public Set<CassandraTable> getCassandraTables() {
		return this.cassandraTables;
	}

	public void setCassandraTables(Set<CassandraTable> cassandraTables) {
		this.cassandraTables = cassandraTables;
	}

}
