package com.vz.cassandraTool.model;
// Generated Oct 14, 2019 5:20:56 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Applications generated by hbm2java
 */
@Entity
@Table(name = "applications")
public class Applications implements java.io.Serializable {

	private String applicationId;
	private Releases releases;
	private String applicationName;
	private String applicationCategory;
	private String applicationManager;
	private String status;
	private Date createdDate;
	private Date updatedDate;
	private Set<Testcycles> testcycleses = new HashSet<Testcycles>(0);
	private Set<ReleaseHistoryLog> releaseHistoryLogs = new HashSet<ReleaseHistoryLog>(0);
	private Set<Userstories> userstorieses = new HashSet<Userstories>(0);

	public Applications() {
	}

	public Applications(String applicationId, Releases releases, String applicationName, String applicationCategory,
			String applicationManager, String status, Date createdDate) {
		this.applicationId = applicationId;
		this.releases = releases;
		this.applicationName = applicationName;
		this.applicationCategory = applicationCategory;
		this.applicationManager = applicationManager;
		this.status = status;
		this.createdDate = createdDate;
	}

	public Applications(String applicationId, Releases releases, String applicationName, String applicationCategory,
			String applicationManager, String status, Date createdDate, Date updatedDate, Set<Testcycles> testcycleses,
			Set<ReleaseHistoryLog> releaseHistoryLogs, Set<Userstories> userstorieses) {
		this.applicationId = applicationId;
		this.releases = releases;
		this.applicationName = applicationName;
		this.applicationCategory = applicationCategory;
		this.applicationManager = applicationManager;
		this.status = status;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.testcycleses = testcycleses;
		this.releaseHistoryLogs = releaseHistoryLogs;
		this.userstorieses = userstorieses;
	}

	@Id

	@Column(name = "application_id", unique = true, nullable = false, length = 20)
	public String getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "release_id", nullable = false)
	public Releases getReleases() {
		return this.releases;
	}

	public void setReleases(Releases releases) {
		this.releases = releases;
	}

	@Column(name = "application_name", nullable = false, length = 50)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@Column(name = "application_category", nullable = false, length = 10)
	public String getApplicationCategory() {
		return this.applicationCategory;
	}

	public void setApplicationCategory(String applicationCategory) {
		this.applicationCategory = applicationCategory;
	}

	@Column(name = "application_manager", nullable = false, length = 50)
	public String getApplicationManager() {
		return this.applicationManager;
	}

	public void setApplicationManager(String applicationManager) {
		this.applicationManager = applicationManager;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applications")
	public Set<Testcycles> getTestcycleses() {
		return this.testcycleses;
	}

	public void setTestcycleses(Set<Testcycles> testcycleses) {
		this.testcycleses = testcycleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applications")
	public Set<ReleaseHistoryLog> getReleaseHistoryLogs() {
		return this.releaseHistoryLogs;
	}

	public void setReleaseHistoryLogs(Set<ReleaseHistoryLog> releaseHistoryLogs) {
		this.releaseHistoryLogs = releaseHistoryLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applications")
	public Set<Userstories> getUserstorieses() {
		return this.userstorieses;
	}

	public void setUserstorieses(Set<Userstories> userstorieses) {
		this.userstorieses = userstorieses;
	}

}
