package com.vz.cassandraTool.model;
// Generated Oct 14, 2019 5:20:56 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "projects")
public class Projects implements java.io.Serializable {

	private String projectId;
	private String projectName;
	private String projectCategory;
	private String projectManager;
	private Date createdDate;
	private Date updatedDate;
	private String status;
	private Set<Releases> releaseses = new HashSet<Releases>(0);

	public Projects() {
	}

	public Projects(String projectId, String projectName, String projectCategory, String projectManager,
			Date createdDate, String status) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.projectCategory = projectCategory;
		this.projectManager = projectManager;
		this.createdDate = createdDate;
		this.status = status;
	}

	public Projects(String projectId, String projectName, String projectCategory, String projectManager,
			Date createdDate, Date updatedDate, String status, Set<Releases> releaseses) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.projectCategory = projectCategory;
		this.projectManager = projectManager;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.status = status;
		this.releaseses = releaseses;
	}

	@Id

	@Column(name = "project_id", unique = true, nullable = false, length = 20)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "project_name", nullable = false, length = 50)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "project_category", nullable = false, length = 10)
	public String getProjectCategory() {
		return this.projectCategory;
	}

	public void setProjectCategory(String projectCategory) {
		this.projectCategory = projectCategory;
	}

	@Column(name = "project_manager", nullable = false, length = 50)
	public String getProjectManager() {
		return this.projectManager;
	}

	public void setProjectManager(String projectManager) {
		this.projectManager = projectManager;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<Releases> getReleaseses() {
		return this.releaseses;
	}

	public void setReleaseses(Set<Releases> releaseses) {
		this.releaseses = releaseses;
	}

}
