package com.vz.cassandraTool.model;
// Generated Oct 14, 2019 5:20:56 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Releases generated by hbm2java
 */
@Entity
@Table(name = "releases")
public class Releases implements java.io.Serializable {

	private String releaseId;
	private Projects projects;
	private Date releaseDate;
	private String releaseName;
	private String releaseDesc;
	private String releaseManager;
	private Date createdDate;
	private Date updatedDate;
	private String status;
	private Set<ReleaseHistory> releaseHistories = new HashSet<ReleaseHistory>(0);
	private Set<ReleaseHistoryLog> releaseHistoryLogs = new HashSet<ReleaseHistoryLog>(0);
	private Set<Applications> applicationses = new HashSet<Applications>(0);

	public Releases() {
	}

	public Releases(String releaseId, Projects projects, Date releaseDate, String releaseName, String releaseDesc,
			String releaseManager, Date createdDate, String status) {
		this.releaseId = releaseId;
		this.projects = projects;
		this.releaseDate = releaseDate;
		this.releaseName = releaseName;
		this.releaseDesc = releaseDesc;
		this.releaseManager = releaseManager;
		this.createdDate = createdDate;
		this.status = status;
	}

	public Releases(String releaseId, Projects projects, Date releaseDate, String releaseName, String releaseDesc,
			String releaseManager, Date createdDate, Date updatedDate, String status,
			Set<ReleaseHistory> releaseHistories, Set<ReleaseHistoryLog> releaseHistoryLogs,
			Set<Applications> applicationses) {
		this.releaseId = releaseId;
		this.projects = projects;
		this.releaseDate = releaseDate;
		this.releaseName = releaseName;
		this.releaseDesc = releaseDesc;
		this.releaseManager = releaseManager;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.status = status;
		this.releaseHistories = releaseHistories;
		this.releaseHistoryLogs = releaseHistoryLogs;
		this.applicationses = applicationses;
	}

	@Id

	@Column(name = "release_id", unique = true, nullable = false, length = 20)
	public String getReleaseId() {
		return this.releaseId;
	}

	public void setReleaseId(String releaseId) {
		this.releaseId = releaseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Projects getProjects() {
		return this.projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_date", nullable = false, length = 29)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "release_name", nullable = false, length = 50)
	public String getReleaseName() {
		return this.releaseName;
	}

	public void setReleaseName(String releaseName) {
		this.releaseName = releaseName;
	}

	@Column(name = "release_desc", nullable = false, length = 200)
	public String getReleaseDesc() {
		return this.releaseDesc;
	}

	public void setReleaseDesc(String releaseDesc) {
		this.releaseDesc = releaseDesc;
	}

	@Column(name = "release_manager", nullable = false, length = 50)
	public String getReleaseManager() {
		return this.releaseManager;
	}

	public void setReleaseManager(String releaseManager) {
		this.releaseManager = releaseManager;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "releases")
	public Set<ReleaseHistory> getReleaseHistories() {
		return this.releaseHistories;
	}

	public void setReleaseHistories(Set<ReleaseHistory> releaseHistories) {
		this.releaseHistories = releaseHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "releases")
	public Set<ReleaseHistoryLog> getReleaseHistoryLogs() {
		return this.releaseHistoryLogs;
	}

	public void setReleaseHistoryLogs(Set<ReleaseHistoryLog> releaseHistoryLogs) {
		this.releaseHistoryLogs = releaseHistoryLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "releases")
	public Set<Applications> getApplicationses() {
		return this.applicationses;
	}

	public void setApplicationses(Set<Applications> applicationses) {
		this.applicationses = applicationses;
	}

}
