package com.vz.cassandraTool.model;
// Generated Oct 14, 2019 5:20:56 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReleaseHistoryLog generated by hbm2java
 */
@Entity
@Table(name = "release_history_log")
public class ReleaseHistoryLog implements java.io.Serializable {

	private ReleaseHistoryLogId id;
	private Applications applications;
	private Releases releases;
	private int userstoryCount;
	private int testcaseCount;
	private int tcExecutedCount;
	private int tcUnexecutedCount;
	private int tcPassedCount;
	private int tcFailedCount;
	private Date createdDate;
	private Date updatedDate;
	private Serializable summaryJson;
	private int tcblockedCount;
	private int naCount;
	private int incompleteCount;
	private String applicationName;
	private String releaseName;

	public ReleaseHistoryLog() {
	}

	public ReleaseHistoryLog(ReleaseHistoryLogId id, Applications applications, Releases releases, int userstoryCount,
			int testcaseCount, int tcExecutedCount, int tcUnexecutedCount, int tcPassedCount, int tcFailedCount,
			Date createdDate, Date updatedDate, int tcblockedCount, int naCount, int incompleteCount) {
		this.id = id;
		this.applications = applications;
		this.releases = releases;
		this.userstoryCount = userstoryCount;
		this.testcaseCount = testcaseCount;
		this.tcExecutedCount = tcExecutedCount;
		this.tcUnexecutedCount = tcUnexecutedCount;
		this.tcPassedCount = tcPassedCount;
		this.tcFailedCount = tcFailedCount;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.tcblockedCount = tcblockedCount;
		this.naCount = naCount;
		this.incompleteCount = incompleteCount;
	}

	public ReleaseHistoryLog(ReleaseHistoryLogId id, Applications applications, Releases releases, int userstoryCount,
			int testcaseCount, int tcExecutedCount, int tcUnexecutedCount, int tcPassedCount, int tcFailedCount,
			Date createdDate, Date updatedDate, Serializable summaryJson, int tcblockedCount, int naCount,
			int incompleteCount, String applicationName, String releaseName) {
		this.id = id;
		this.applications = applications;
		this.releases = releases;
		this.userstoryCount = userstoryCount;
		this.testcaseCount = testcaseCount;
		this.tcExecutedCount = tcExecutedCount;
		this.tcUnexecutedCount = tcUnexecutedCount;
		this.tcPassedCount = tcPassedCount;
		this.tcFailedCount = tcFailedCount;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.summaryJson = summaryJson;
		this.tcblockedCount = tcblockedCount;
		this.naCount = naCount;
		this.incompleteCount = incompleteCount;
		this.applicationName = applicationName;
		this.releaseName = releaseName;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "syncRelDate", column = @Column(name = "sync_rel_date", nullable = false, length = 29)),
			@AttributeOverride(name = "releaseId", column = @Column(name = "release_id", nullable = false, length = 50)),
			@AttributeOverride(name = "applicationId", column = @Column(name = "application_id", nullable = false, length = 50)) })
	public ReleaseHistoryLogId getId() {
		return this.id;
	}

	public void setId(ReleaseHistoryLogId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id", nullable = false, insertable = false, updatable = false)
	public Applications getApplications() {
		return this.applications;
	}

	public void setApplications(Applications applications) {
		this.applications = applications;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "release_id", nullable = false, insertable = false, updatable = false)
	public Releases getReleases() {
		return this.releases;
	}

	public void setReleases(Releases releases) {
		this.releases = releases;
	}

	@Column(name = "userstory_count", nullable = false)
	public int getUserstoryCount() {
		return this.userstoryCount;
	}

	public void setUserstoryCount(int userstoryCount) {
		this.userstoryCount = userstoryCount;
	}

	@Column(name = "testcase_count", nullable = false)
	public int getTestcaseCount() {
		return this.testcaseCount;
	}

	public void setTestcaseCount(int testcaseCount) {
		this.testcaseCount = testcaseCount;
	}

	@Column(name = "tc_executed_count", nullable = false)
	public int getTcExecutedCount() {
		return this.tcExecutedCount;
	}

	public void setTcExecutedCount(int tcExecutedCount) {
		this.tcExecutedCount = tcExecutedCount;
	}

	@Column(name = "tc_unexecuted_count", nullable = false)
	public int getTcUnexecutedCount() {
		return this.tcUnexecutedCount;
	}

	public void setTcUnexecutedCount(int tcUnexecutedCount) {
		this.tcUnexecutedCount = tcUnexecutedCount;
	}

	@Column(name = "tc_passed_count", nullable = false)
	public int getTcPassedCount() {
		return this.tcPassedCount;
	}

	public void setTcPassedCount(int tcPassedCount) {
		this.tcPassedCount = tcPassedCount;
	}

	@Column(name = "tc_failed_count", nullable = false)
	public int getTcFailedCount() {
		return this.tcFailedCount;
	}

	public void setTcFailedCount(int tcFailedCount) {
		this.tcFailedCount = tcFailedCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "summary_json")
	public Serializable getSummaryJson() {
		return this.summaryJson;
	}

	public void setSummaryJson(Serializable summaryJson) {
		this.summaryJson = summaryJson;
	}

	@Column(name = "tcblocked_count", nullable = false)
	public int getTcblockedCount() {
		return this.tcblockedCount;
	}

	public void setTcblockedCount(int tcblockedCount) {
		this.tcblockedCount = tcblockedCount;
	}

	@Column(name = "na_count", nullable = false)
	public int getNaCount() {
		return this.naCount;
	}

	public void setNaCount(int naCount) {
		this.naCount = naCount;
	}

	@Column(name = "incomplete_count", nullable = false)
	public int getIncompleteCount() {
		return this.incompleteCount;
	}

	public void setIncompleteCount(int incompleteCount) {
		this.incompleteCount = incompleteCount;
	}

	@Column(name = "application_name", length = 50)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@Column(name = "release_name", length = 50)
	public String getReleaseName() {
		return this.releaseName;
	}

	public void setReleaseName(String releaseName) {
		this.releaseName = releaseName;
	}

}
