package com.vz.cassandraTool.model;
// Generated Oct 14, 2019 5:20:56 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReleaseHistoryLogId generated by hbm2java
 */
@Embeddable
public class ReleaseHistoryLogId implements java.io.Serializable {

	private Date syncRelDate;
	private String releaseId;
	private String applicationId;

	public ReleaseHistoryLogId() {
	}

	public ReleaseHistoryLogId(Date syncRelDate, String releaseId, String applicationId) {
		this.syncRelDate = syncRelDate;
		this.releaseId = releaseId;
		this.applicationId = applicationId;
	}

	@Column(name = "sync_rel_date", nullable = false, length = 29)
	public Date getSyncRelDate() {
		return this.syncRelDate;
	}

	public void setSyncRelDate(Date syncRelDate) {
		this.syncRelDate = syncRelDate;
	}

	@Column(name = "release_id", nullable = false, length = 50)
	public String getReleaseId() {
		return this.releaseId;
	}

	public void setReleaseId(String releaseId) {
		this.releaseId = releaseId;
	}

	@Column(name = "application_id", nullable = false, length = 50)
	public String getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReleaseHistoryLogId))
			return false;
		ReleaseHistoryLogId castOther = (ReleaseHistoryLogId) other;

		return ((this.getSyncRelDate() == castOther.getSyncRelDate()) || (this.getSyncRelDate() != null
				&& castOther.getSyncRelDate() != null && this.getSyncRelDate().equals(castOther.getSyncRelDate())))
				&& ((this.getReleaseId() == castOther.getReleaseId()) || (this.getReleaseId() != null
						&& castOther.getReleaseId() != null && this.getReleaseId().equals(castOther.getReleaseId())))
				&& ((this.getApplicationId() == castOther.getApplicationId())
						|| (this.getApplicationId() != null && castOther.getApplicationId() != null
								&& this.getApplicationId().equals(castOther.getApplicationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSyncRelDate() == null ? 0 : this.getSyncRelDate().hashCode());
		result = 37 * result + (getReleaseId() == null ? 0 : this.getReleaseId().hashCode());
		result = 37 * result + (getApplicationId() == null ? 0 : this.getApplicationId().hashCode());
		return result;
	}

}
