package com.vz.cassandraTool.model;
// Generated Oct 14, 2019 5:20:56 PM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Statsbyreleaseslog generated by hbm2java
 */
@Entity
@Table(name = "statsbyreleaseslog")
public class Statsbyreleaseslog implements java.io.Serializable {

	private int id;
	private Serializable request;
	private Serializable response;
	private String syncStatus;
	private Date createdDate;
	private Date updatedDate;

	public Statsbyreleaseslog() {
	}

	public Statsbyreleaseslog(int id, String syncStatus, Date createdDate) {
		this.id = id;
		this.syncStatus = syncStatus;
		this.createdDate = createdDate;
	}

	public Statsbyreleaseslog(int id, Serializable request, Serializable response, String syncStatus, Date createdDate,
			Date updatedDate) {
		this.id = id;
		this.request = request;
		this.response = response;
		this.syncStatus = syncStatus;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "request")
	public Serializable getRequest() {
		return this.request;
	}

	public void setRequest(Serializable request) {
		this.request = request;
	}

	@Column(name = "response")
	public Serializable getResponse() {
		return this.response;
	}

	public void setResponse(Serializable response) {
		this.response = response;
	}

	@Column(name = "sync_status", nullable = false, length = 10)
	public String getSyncStatus() {
		return this.syncStatus;
	}

	public void setSyncStatus(String syncStatus) {
		this.syncStatus = syncStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
