package com.vz.cassandraTool.model;
// Generated Oct 14, 2019 5:20:56 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Testcycles generated by hbm2java
 */
@Entity
@Table(name = "testcycles")
public class Testcycles implements java.io.Serializable {

	private String testcycleId;
	private Applications applications;
	private String status;
	private String testcycleType;
	private String testcycleName;
	private String testcycleDesc;
	private Date createdDate;
	private Date updatedDate;
	private Date assignedDate;
	private String assignedto;
	private String createdby;
	private String updatedby;
	private String assignedby;
	private Set<Testsuites> testsuiteses = new HashSet<Testsuites>(0);

	public Testcycles() {
	}

	public Testcycles(String testcycleId, Applications applications, String status, String testcycleType,
			String testcycleName, String testcycleDesc, Date createdDate, String assignedto, String createdby,
			String updatedby, String assignedby) {
		this.testcycleId = testcycleId;
		this.applications = applications;
		this.status = status;
		this.testcycleType = testcycleType;
		this.testcycleName = testcycleName;
		this.testcycleDesc = testcycleDesc;
		this.createdDate = createdDate;
		this.assignedto = assignedto;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.assignedby = assignedby;
	}

	public Testcycles(String testcycleId, Applications applications, String status, String testcycleType,
			String testcycleName, String testcycleDesc, Date createdDate, Date updatedDate, Date assignedDate,
			String assignedto, String createdby, String updatedby, String assignedby, Set<Testsuites> testsuiteses) {
		this.testcycleId = testcycleId;
		this.applications = applications;
		this.status = status;
		this.testcycleType = testcycleType;
		this.testcycleName = testcycleName;
		this.testcycleDesc = testcycleDesc;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.assignedDate = assignedDate;
		this.assignedto = assignedto;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.assignedby = assignedby;
		this.testsuiteses = testsuiteses;
	}

	@Id

	@Column(name = "testcycle_id", unique = true, nullable = false, length = 20)
	public String getTestcycleId() {
		return this.testcycleId;
	}

	public void setTestcycleId(String testcycleId) {
		this.testcycleId = testcycleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id", nullable = false)
	public Applications getApplications() {
		return this.applications;
	}

	public void setApplications(Applications applications) {
		this.applications = applications;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "testcycle_type", nullable = false, length = 10)
	public String getTestcycleType() {
		return this.testcycleType;
	}

	public void setTestcycleType(String testcycleType) {
		this.testcycleType = testcycleType;
	}

	@Column(name = "testcycle_name", nullable = false, length = 50)
	public String getTestcycleName() {
		return this.testcycleName;
	}

	public void setTestcycleName(String testcycleName) {
		this.testcycleName = testcycleName;
	}

	@Column(name = "testcycle_desc", nullable = false, length = 200)
	public String getTestcycleDesc() {
		return this.testcycleDesc;
	}

	public void setTestcycleDesc(String testcycleDesc) {
		this.testcycleDesc = testcycleDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "assigned_date", length = 29)
	public Date getAssignedDate() {
		return this.assignedDate;
	}

	public void setAssignedDate(Date assignedDate) {
		this.assignedDate = assignedDate;
	}

	@Column(name = "assignedto", nullable = false, length = 50)
	public String getAssignedto() {
		return this.assignedto;
	}

	public void setAssignedto(String assignedto) {
		this.assignedto = assignedto;
	}

	@Column(name = "createdby", nullable = false, length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby", nullable = false, length = 50)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "assignedby", nullable = false, length = 50)
	public String getAssignedby() {
		return this.assignedby;
	}

	public void setAssignedby(String assignedby) {
		this.assignedby = assignedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testcycles")
	public Set<Testsuites> getTestsuiteses() {
		return this.testsuiteses;
	}

	public void setTestsuiteses(Set<Testsuites> testsuiteses) {
		this.testsuiteses = testsuiteses;
	}

}
