package com.vz.cassandraTool.model;
// Generated Oct 14, 2019 5:20:56 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userstories generated by hbm2java
 */
@Entity
@Table(name = "userstories")
public class Userstories implements java.io.Serializable {

	private String userstoryId;
	private Applications applications;
	private String status;
	private String userstoryName;
	private String userstoryDesc;
	private Date createdDate;
	private Date updatedDate;
	private Date assignedDate;
	private String assignedto;
	private String createdby;
	private String updatedby;
	private String assignedby;

	public Userstories() {
	}

	public Userstories(String userstoryId, Applications applications, String status, String userstoryName,
			String userstoryDesc, Date createdDate, String assignedto, String createdby, String updatedby,
			String assignedby) {
		this.userstoryId = userstoryId;
		this.applications = applications;
		this.status = status;
		this.userstoryName = userstoryName;
		this.userstoryDesc = userstoryDesc;
		this.createdDate = createdDate;
		this.assignedto = assignedto;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.assignedby = assignedby;
	}

	public Userstories(String userstoryId, Applications applications, String status, String userstoryName,
			String userstoryDesc, Date createdDate, Date updatedDate, Date assignedDate, String assignedto,
			String createdby, String updatedby, String assignedby) {
		this.userstoryId = userstoryId;
		this.applications = applications;
		this.status = status;
		this.userstoryName = userstoryName;
		this.userstoryDesc = userstoryDesc;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.assignedDate = assignedDate;
		this.assignedto = assignedto;
		this.createdby = createdby;
		this.updatedby = updatedby;
		this.assignedby = assignedby;
	}

	@Id

	@Column(name = "userstory_id", unique = true, nullable = false, length = 20)
	public String getUserstoryId() {
		return this.userstoryId;
	}

	public void setUserstoryId(String userstoryId) {
		this.userstoryId = userstoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "application_id", nullable = false)
	public Applications getApplications() {
		return this.applications;
	}

	public void setApplications(Applications applications) {
		this.applications = applications;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "userstory_name", nullable = false, length = 50)
	public String getUserstoryName() {
		return this.userstoryName;
	}

	public void setUserstoryName(String userstoryName) {
		this.userstoryName = userstoryName;
	}

	@Column(name = "userstory_desc", nullable = false, length = 200)
	public String getUserstoryDesc() {
		return this.userstoryDesc;
	}

	public void setUserstoryDesc(String userstoryDesc) {
		this.userstoryDesc = userstoryDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "assigned_date", length = 29)
	public Date getAssignedDate() {
		return this.assignedDate;
	}

	public void setAssignedDate(Date assignedDate) {
		this.assignedDate = assignedDate;
	}

	@Column(name = "assignedto", nullable = false, length = 50)
	public String getAssignedto() {
		return this.assignedto;
	}

	public void setAssignedto(String assignedto) {
		this.assignedto = assignedto;
	}

	@Column(name = "createdby", nullable = false, length = 50)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "updatedby", nullable = false, length = 50)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "assignedby", nullable = false, length = 50)
	public String getAssignedby() {
		return this.assignedby;
	}

	public void setAssignedby(String assignedby) {
		this.assignedby = assignedby;
	}

}
